### ISSUE TITLE
node-odbc doesn't build since node::EventEmitter was removed

### ISSUE THREAD

**Issue by bbigras** [w1nk/node-odbc#11]
While trying to build node-odbc I got :

```
../src/Database.cpp:20:25: error: node_events.h: No such file or directory
```

I think it's since [node::EventEmitter was removed from node.js](https://github.com/joyent/node/commit/4ef8f06fe62edb74fded0e817266cb6398e69f36)  which could be about two releases ago but I only got it today when I upgraded to 0.6.0 (stable).

```
$ ./build.sh
Setting srcdir to                        : /home/bbigras/project/node_modules/node-odbc
Setting blddir to                        : /home/bbigras/project/node_modules/node-odbc/build
Checking for program g++ or c++          : /usr/bin/g++
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : not found
Checking for node prefix                 : ok /usr
Checking for library odbc                : yes
'configure' finished successfully (1.002s)
Waf: Entering directory `/home/bbigras/project/node_modules/node-odbc/build'
[1/2] cxx: src/Database.cpp -> build/Release/src/Database_1.o
../src/Database.cpp:20:25: error: node_events.h: No such file or directory
In file included from ../src/Database.cpp:23:
../src/Database.h:34: error: expected class-name before ‘{’ token
../src/Database.h: In constructor ‘Database::Database()’:
../src/Database.h:41: error: class ‘Database’ does not have any field named ‘EventEmitter’
../src/Database.cpp: In static member function ‘static void Database::Init(v8::Handle<v8::Object>)’:
../src/Database.cpp:45: error: ‘EventEmitter’ has not been declared
../src/Database.cpp: In static member function ‘static v8::Handle<v8::Value> Database::New(const v8::Arguments&)’:
../src/Database.cpp:62: error: ‘class Database’ has no member named ‘Wrap’
../src/Database.cpp: In static member function ‘static int Database::EIO_AfterOpen(eio_req*)’:
../src/Database.cpp:80: error: ‘class Database’ has no member named ‘Unref’
../src/Database.cpp:87: error: ‘class Database’ has no member named ‘Emit’
../src/Database.cpp: In static member function ‘static v8::Handle<v8::Value> Database::Open(const v8::Arguments&)’:
../src/Database.cpp:148: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Database.cpp:148: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/Database.cpp:151: error: ‘class Database’ has no member named ‘Ref’
../src/Database.cpp: In static member function ‘static int Database::EIO_AfterClose(eio_req*)’:
../src/Database.cpp:172: error: ‘class Database’ has no member named ‘Unref’
../src/Database.cpp:179: error: ‘class Database’ has no member named ‘Emit’
../src/Database.cpp: In static member function ‘static v8::Handle<v8::Value> Database::Close(const v8::Arguments&)’:
../src/Database.cpp:216: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Database.cpp:216: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/Database.cpp:219: error: ‘class Database’ has no member named ‘Ref’
../src/Database.cpp: In static member function ‘static int Database::EIO_AfterQuery(eio_req*)’:
../src/Database.cpp:257: error: ‘class Database’ has no member named ‘Emit’
../src/Database.cpp:260: error: ‘class Database’ has no member named ‘Emit’
../src/Database.cpp:288: error: ‘class Database’ has no member named ‘Emit’
../src/Database.cpp:353: error: ‘class Database’ has no member named ‘Emit’
../src/Database.cpp:461: error: ‘class Database’ has no member named ‘Emit’
../src/Database.cpp:469: error: ‘class Database’ has no member named ‘Unref’
../src/Database.cpp: In static member function ‘static v8::Handle<v8::Value> Database::Query(const v8::Arguments&)’:
../src/Database.cpp:530: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Database.cpp:530: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/Database.cpp:533: error: ‘class Database’ has no member named ‘Ref’
../src/Database.cpp: In static member function ‘static v8::Handle<v8::Value> Database::Tables(const v8::Arguments&)’:
../src/Database.cpp:608: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Database.cpp:608: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/Database.cpp:611: error: ‘class Database’ has no member named ‘Ref’
../src/Database.cpp: In static member function ‘static v8::Handle<v8::Value> Database::Columns(const v8::Arguments&)’:
../src/Database.cpp:687: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Database.cpp:687: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/Database.cpp:690: error: ‘class Database’ has no member named ‘Ref’
Waf: Leaving directory `/home/bbigras/project/node_modules/node-odbc/build'
Build failed:  -> task failed (err #1):
        {task: cxx Database.cpp -> Database_1.o}
```

**Comment by wankdanker** [comment]
Hey brunoqc, I have a branch that has this fixed: https://github.com/wankdanker/node-odbc/tree/node-v0.5.x-bind-params, if you clone from there, you shouldn't have any problems. I will be merging this soon.

**Comment by bbigras** [comment]
I tried without success.

Did I miss anything?

```
bbigras@ubuntu-machinage:~/test-odbc$ git clone https://github.com/wankdanker/node-odbc.git
Initialized empty Git repository in /home/bbigras/test-odbc/node-odbc/.git/
[...]
Resolving deltas: 100% (105/105), done.
bbigras@ubuntu-machinage:~/test-odbc$ cd node-odbc/
bbigras@ubuntu-machinage:~/test-odbc/node-odbc$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/node-v0.5.x
  remotes/origin/node-v0.5.x-bind-params
bbigras@ubuntu-machinage:~/test-odbc/node-odbc$ git checkout remotes/origin/node-v0.5.x-bind-params
Note: checking out 'remotes/origin/node-v0.5.x-bind-params'.
[...]
HEAD is now at 4f47f0a... Merge branch 'master' of git://github.com/w1nk/node-odbc into node-v0.5.x-bind-params
bbigras@ubuntu-machinage:~/test-odbc/node-odbc$ ./build.sh
Setting srcdir to                        : /home/bbigras/test-odbc/node-odbc
Setting blddir to                        : /home/bbigras/test-odbc/node-odbc/build
Checking for program g++ or c++          : /usr/bin/g++
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : not found
Checking for node prefix                 : ok /usr
Checking for library odbc                : yes
'configure' finished successfully (0.596s)
Waf: Entering directory `/home/bbigras/test-odbc/node-odbc/build'
[1/2] cxx: src/Database.cpp -> build/Release/src/Database_1.o
../src/Database.cpp:20:25: error: node_events.h: No such file or directory
Waf: Leaving directory `/home/bbigras/test-odbc/node-odbc/build'
Build failed:  -> task failed (err #1):
        {task: cxx Database.cpp -> Database_1.o}
bbigras@ubuntu-machinage:~/test-odbc/node-odbc$
```

**Comment by wankdanker** [comment]
Hmmm. Do you you `make install` node 0.6?

**Comment by bbigras** [comment]
I use a precompiled node.js binary from an [Ubuntu ppa](https://launchpad.net/~chris-lea/+archive/node.js/).

Did you see the commit https://github.com/joyent/node/commit/4ef8f06fe62edb74fded0e817266cb6398e69f36 which removed node_events.h ?

**Comment by wankdanker** [comment]
I hadn't seen that. Thank you for pointing that out. I always compile my own and I must have had an old node_events.h still lingering. Anyway, I removed references to node_events.h and everything still works. I have pushed all my changes to my master branch, so if you clone from there and give it a try, I'm thinking you'll have better luck.

**Comment by bbigras** [comment]
It's working again. Thanks!
